#!/bin/bash
#
# Configure a ubuntu based system for jpaas development

# usage: clone url [ parent-dir-of-repo [ folder-containing-zips ] ]
clone() {
  url=$1
  repoDir=${2-~/git}
  tarDir=${3-/media/sf_Shared/git/backups}
  repo=${url##*/}
  dir=${repo%.git}

  mkdir -p "$repoDir"
  if [ ! -d "$repoDir/$dir" ] ;then
    if [ -f "$tarDir/$dir.tar" ] ;then
      tar -C "$repoDir" -xf "$tarDir/$dir.tar"
      git -C "$repoDir/$dir" fetch --all --recurse-submodules
      git -C "$repoDir/$dir" pull --recurse-submodules
    else
      git clone -q --recursive "$url" "$repoDir/$dir"
    fi
  else
    git -C "$repoDir/$dir" fetch --all --recurse-submodules
  fi
}

read -p "Enter directory where to find sap installations: " -e -i "/mnt/perm/sap/install" install_src

# setup a jpaas sdk
find "$install_src" -maxdepth 1 -type f -name 'neo-sdk*.zip' -printf '%P\n' | sed -e 's/\.zip//' | while read sdk ;do
	if [ ! -d ~/jpaas/$sdk ] ;then
		mkdir -p ~/jpaas/$sdk
		(cd ~/jpaas/$sdk; unzip -q "$install_src"/$sdk.zip)
	fi
	[ -f ~/bin/neo ] || ln -s ~/jpaas/$sdk/tools/neo.sh ~/bin/neo
done

# setup mavens settings.xml
if [ ! -f ~/.m2/settings.xml.jpaas ] ;then
	mkdir -p ~/.m2
	wget -O ~/.m2/settings.xml.jpaas http://nexus.wdf.sap.corp:8081/nexus/service/local/templates/settings/LeanDI/content
	sed -r -i 's/\r//' ~/.m2/settings.xml.jpaas
fi
if [ -f ~/.m2/settings.xml.jpaas -a -f ~/.m2/settings_sap_proxy.xml ] ;then
	cat ~/.m2/settings.xml.jpaas ~/.m2/settings_sap_proxy.xml >~/.m2/settings_sap_proxy.xml.jpaas
	sed -r -i '/<\/settings>/{ N; s/<\/settings>\n<settings>// }' ~/.m2/settings_sap_proxy.xml.jpaas
fi
cmp ~/.m2/settings.xml ~/.m2/settings.xml.jpaas && rm ~/.m2/settings.xml
cmp ~/.m2/settings.xml ~/.m2/settings_sap_proxy.xml && rm ~/.m2/settings.xml
[ -f ~/.m2/settings.xml ] || cp ~/.m2/settings_sap_proxy.xml.jpaas ~/.m2/settings.xml

export GIT_SSL_NO_VERIFY=true

mkdir -p ~/git/orion

# clone metering, orion, accountPage, appdesigner, hcproxy, cloudrepo
clone https://git.wdf.sap.corp:8080/NGJP/Services/metering
clone https://git.wdf.sap.corp:8080/NGJP/LeanDI/jpaas.orion.git ~/git/orion
clone https://git.wdf.sap.corp:8080/NGJP/LeanDI/org.eclipse.orion.client.git ~/git/orion
clone https://git.wdf.sap.corp:8080/NGJP/LeanDI/org.eclipse.orion.server.git ~/git/orion
clone https://git.wdf.sap.corp:8080/NGJP/JPaaS/com.sap.core.account.git
clone https://git.wdf.sap.corp:8080/com.sap.core.hcproxy.git
clone https://git.wdf.sap.corp:8080/NGJP/LeanDI/Git/com.sap.core.cloudrepo.git
git -C ~/git/gerrit remote add sap https://git.wdf.sap.corp:8080/NGP/LDI/gerrit-internal && git -C ~/git/gerrit fetch --all --recurse-submodules
git -C ~/git/jgit remote add sap https://git.wdf.sap.corp:8080/NGP/LDI/jgit && git -C ~/git/jgit fetch --all --recurse-submodules

[ -f ~/lib/commit-msg ] || { mkdir -p ~/lib; wget -P ~/lib https://git.eclipse.org/r/tools/hooks/commit-msg; chmod +x ~/lib/commit-msg; }
[ -f ~/git/metering/.git/hooks/commit-msg ] || { git -C ~/git/metering config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/metering/.git/hooks; }
[ -f ~/git/orion/jpaas.orion/.git/hooks/commit-msg ] || { git -C ~/git/orion/jpaas.orion config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/orion/jpaas.orion/.git/hooks; }
[ -f ~/git/orion/org.eclipse.orion.client/.git/hooks/commit-msg ] || { git -C ~/git/orion/org.eclipse.orion.client config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/orion/org.eclipse.orion.client/.git/hooks; }
[ -f ~/git/orion/org.eclipse.orion.server/.git/hooks/commit-msg ] || { git -C ~/git/orion/org.eclipse.orion.server config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/orion/org.eclipse.orion.server/.git/hooks; }
[ -f ~/git/com.sap.core.account/.git/hooks/commit-msg ] || { git -C ~/git/com.sap.core.account config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/com.sap.core.account/.git/hooks; }
[ -f ~/git/com.sap.core.hcproxy/.git/hooks/commit-msg ] || { git -C ~/git/com.sap.core.hcproxy config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/com.sap.core.hcproxy/.git/hooks; }
[ -f ~/git/com.sap.core.cloudrepo/.git/hooks/commit-msg ] || { git -C ~/git/com.sap.core.cloudrepo config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/com.sap.core.cloudrepo/.git/hooks; }

# build the cloned repos
mvn -s ~/.m2/settings.xml.jpaas -f ~/git/metering/com.sap.core.metering.parent/pom.xml -q install -DskipTests=true
mvn -s ~/.m2/settings.xml.jpaas -f ~/git/orion/org.eclipse.orion.client/pom.xml -q clean install -DskipTests=true
mvn -s ~/.m2/settings.xml.jpaas -f ~/git/orion/org.eclipse.orion.server/pom.xml -q clean install -DskipTests=true
mvn -s ~/.m2/settings.xml.jpaas -f ~/git/orion/jpaas.orion/pom.xml -q clean install -DskipTests=true
mvn -s ~/.m2/settings.xml.jpaas -f ~/git/com.sap.core.account/pom.xml -q install -DskipTests=true
mvn -s ~/.m2/settings.xml.jpaas -f ~/git/com.sap.core.hcproxy/pom.xml -q install -DskipTests=true
mvn -s ~/.m2/settings.xml.jpaas -f ~/git/com.sap.core.cloudrepo/com.sap.jgit.extensions/pom.xml -q install -DskipTests=true

# install SAP Tools in luna
eclipse -application org.eclipse.equinox.p2.director \
  -r "http://download.eclipse.org/releases/luna,https://tools.neo.ondemand.com/luna,http://download.eclipse.org/m2e-wtp/releases" \
  -i com.sap.core.tools.eclipse.help.feature.feature.group,com.sap.core.tools.eclipse.server.feature.feature.group,com.sap.jvm.profiling.feature.group,com.sap.ide.support.feature.feature.group,com.sap.ide.ui5.cloud.feature.feature.group,org.eclipse.m2e.feature.feature.group
exit
