#!/bin/bash
#
# Configure a Lubuntu system to work inside the SAP intranet.

sudo -E apt-get -q=2 install libnss3-tools
read -p "Folder containing SAPNetCA.crt: " crtFolder

for i in SAPNetCA SAPNetCA_G2 "SAP Global Root CA" ;do
	[ -f "$crtFolder/$i.crt" ] && sudo cp "$crtFolder/$i.crt" /usr/local/share/ca-certificates
	sudo chmod 444 "/usr/local/share/ca-certificates/$i.crt"
done
sudo dpkg-reconfigure ca-certificates
sudo update-ca-certificates
[ -e $HOME/.pki/nssdb ] || ( mkdir -p $HOME/.pki/nssdb ; cd $HOME/.pki/nssdb ; certutil -N -d sql:. )
for i in SAPNetCA SAPNetCA_G2 "SAP Global Root CA" ;do
	certutil -d sql:$HOME/.pki/nssdb -A -t TC -n "$i" -i "/usr/local/share/ca-certificates/$i.crt"
done

# add wdf.sap.corp as a default domain
if ! grep "^search" /etc/resolvconf/resolv.conf.d/base ;then
	sudo sh -c 'echo "search wdf.sap.corp" >> /etc/resolvconf/resolv.conf.d/base'
fi

