#!/bin/bash
#
# chris specific configurations

# usage: clone url [ parent-dir-of-repo [ folder-containing-zips ] ]
clone() {
  url=$1
  repoDir=${2-~/git}
  tarDir=${3-/media/sf_Shared/git/backups}
  repo=${url##*/}
  dir=${repo%.git}

  mkdir -p "$repoDir"
  if [ ! -d "$repoDir/$dir" ] ;then
    if [ -f "$tarDir/$dir.tar" ] ;then
      tar -C "$repoDir" -xf "$tarDir/$dir.tar"
      git -C "$repoDir/$dir" fetch --all --recurse-submodules
      git -C "$repoDir/$dir" pull --recurse-submodules
    else
      git clone -q --recursive "$url" "$repoDir/$dir"
    fi
  else
    git -C "$repoDir/$dir" fetch --all --recurse-submodules
  fi
}

if [ -f ~/.netrc ] ;then
	echo "Don't write ~/.netrc because it already exists"
else
	read -s -p "Enter password for P1323864547 at servermetermeter-meter.prod.jpaas.sapbydesign.com: " epass
	echo -e "machine servermetermeter-meter.prod.jpaas.sapbydesign.com\nlogin P1323864547\npassword $epass" >> ~/.netrc
	echo
	read -s -p "Enter password for d032780 at git.wdf.sap.corp: " epass
	echo -e "machine git.wdf.sap.corp\nlogin d032780\npassword $epass" >> ~/.netrc
	echo
	read -s -p "Enter password for d032780 at git.neo.ondemand.com: " epass
	echo -e "machine git.neo.ondemand.com\nlogin d032780\npassword $epass" >> ~/.netrc
	echo
	read -s -p "Enter password for chalstrick at git.eclipse.org: " epass
	echo -e "machine git.eclipse.org\nlogin chalstrick\npassword $epass" >> ~/.netrc
	echo
	read -s -p "Enter password for chalstrick at github.com: " epass
	echo -e "machine github.com\nlogin chalstrick\npassword $epass" >> ~/.netrc
	chmod 600 ~/.netrc
fi

clone http://github.com/chalstrick/chrisFiles && ~/git/chrisFiles/git/setGitConfig.sh
[ -f ~/.vimrc ] || cp ~/git/chrisFiles/vim/_vimrc ~/.vimrc

(cd ~/git/jgit && git config remote.origin.pushurl https://chalstrick@git.eclipse.org/r/jgit/jgit.git && git remote add sap https://d032780@git.wdf.sap.corp:8080/NGP/LDI/jgit && git remote add github https://chalstrick@github.com/chalstrick/jgit.git && git fetch github sap && git config remote.sap.push HEAD:refs/for/master)
(cd ~/git/egit && git config remote.origin.pushurl https://chalstrick@git.eclipse.org/r/egit/egit.git && git remote add github https://chalstrick@github.com/chalstrick/egit.git && git fetch github)
(cd ~/git/gerrit && git remote add sap https://d032780@git.wdf.sap.corp:8080/NGP/LDI/gerrit-internal && git fetch sap && git config remote.sap.push HEAD:refs/for/master)
git config -f ~/git/egit-pde/.git/config remote.origin.pushurl https://chalstrick@git.eclipse.org/r/egit/egit-pde.git
git config -f ~/git/egit-github/.git/config remote.origin.pushurl https://chalstrick@git.eclipse.org/r/egit/egit-github.git

read -p "import certificates (your and sap) into firefox and chrome"
read -p "import ssh keys to ~/.ssh"
read -p "import bookmarks into firefox and chrome"
read -p "login once in firefox and chrome to google, eclipse, github, sap-gerrit, sap-intranet"
read -p "import chrisFiles into eclipse"

ssh gerrit@git.wdf.sap.corp
