#!/bin/bash
#
# Configure a ubuntu based system to contain my optional software packages

# install applications
sudo -E apt-get -q=2 install python-software-properties python g++ make vim vim-gui-common visualvm curl terminator openjdk-6-jdk chromium-browser mc nfs-common nfs-kernel-server
sudo service rpcbind restart

# setup nfs exports
[ -e /export ] || sudo mkdir -m 777 /export
[ -e /export/public ] || sudo mkdir -m 777 /export/public
grep "/export/public" /etc/exports || sudo sh -c "echo '/export/public	*(rw,sync,no_root_squash)' >>/etc/exports"
sudo service nfs-kernel-server start

# setup nfs imports
[ -e /mnt ] || sudo mkdir -m 777 /mnt
[ -e /mnt/localhost ] || sudo mkdir -m 777 /mnt/localhost
[ -e /mnt/localhost/public ] || sudo mkdir -m 777 /mnt/localhost/public
grep "/mnt/localhost/public" /etc/fstab || sudo sh -c "echo 'localhost:/export/public   /mnt/localhost/public   nfs    auto  0  0' >>/etc/fstab"
sudo mount /mnt/localhost/public

# install cdt in eclipse
eclipse -application org.eclipse.equinox.p2.director \
  -r "http://download.eclipse.org/releases/luna" \
  -i org.eclipse.cdt.autotools.feature.group,org.eclipse.cdt.feature.group

read -p "Open new Eclipse workspace workspace.native and import C project ~/git/git"
