#!/bin/bash
#
# Clone my favourite git repos

clone() {
  url=$1
  repoDir=${2-~/git}
  tarDir=${3-/media/sf_Shared/git/backups}
  repo=${url##*/}
  dir=${repo%.git}

  mkdir -p "$repoDir"
  if [ ! -d "$repoDir/$dir" ] ;then
    if [ -f "$tarDir/$dir.tar" ] ;then
      tar -C "$repoDir" -xf "$tarDir/$dir.tar"
      git -C "$repoDir/$dir" fetch --all --recurse-submodules
      git -C "$repoDir/$dir" pull --recurse-submodules
    else
      git clone -q --recursive "$url" "$repoDir/$dir"
    fi
 fi
}
 
# get git
sudo -E apt-get -q=2 install git gitk 

# clone/fetch linux, git, e/jgit, gerrit, buck
clone https://github.com/torvalds/linux.git
clone https://gerrit.googlesource.com/gerrit
clone https://github.com/git/git.git
clone https://git.eclipse.org/r/jgit/jgit
clone https://git.eclipse.org/r/egit/egit
clone https://gerrit.googlesource.com/buck

# configure jgit,egit,gerrit to work with gerrit
[ -f ~/lib/commit-msg ] || { mkdir -p ~/lib; wget -O ~/lib/commit-msg https://git.eclipse.org/r/tools/hooks/commit-msg; chmod +x ~/lib/commit-msg; }
[ -f ~/git/jgit/.git/hooks/commit-msg ] || { git -C ~/git/jgit config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/jgit/.git/hooks; }
[ -f ~/git/egit/.git/hooks/commit-msg ] || { git -C ~/git/egit config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/egit/.git/hooks; }
[ -f ~/git/gerrit/.git/hooks/commit-msg ] || { git -C ~/git/gerrit config remote.origin.push HEAD:refs/for/master; cp ~/lib/commit-msg ~/git/gerrit/.git/hooks; }
