#!/bin/bash
#
# Configure a ubuntu based system to contain my optional software packages

# update the package index database
sudo -E apt-get -q=2 update

# install applications
sudo -E apt-get -q=2 install python-software-properties python g++ make vim vim-gui-common visualvm curl terminator openjdk-6-jdk chromium-browser

# install cdt in eclipse
eclipse -application org.eclipse.equinox.p2.director \
  -r "http://download.eclipse.org/releases/kepler" \
  -i org.eclipse.cdt.autotools.feature.group,org.eclipse.cdt.feature.group

read -p "Open new Eclipse workspace workspace.native and import C project ~/git/git"
